from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def generate_report(kpis, ai_summary, output_path):
    """
    Generate a professional executive PDF report.
    """

    doc = SimpleDocTemplate(output_path)

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    heading = styles["Heading1"]

    body = styles["BodyText"]

    elements = []

    # ------------------------------------------------
    # Cover
    # ------------------------------------------------

    elements.append(
        Paragraph(
            "<b>InsightIQ</b>",
            title_style,
        )
    )

    elements.append(
        Paragraph(
            "AI-Powered Retail Analytics Platform",
            styles["Heading2"],
        )
    )

    elements.append(
        Paragraph(
            "<b>Executive Business Report</b>",
            styles["Heading2"],
        )
    )

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            f"Generated on: {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
            body,
        )
    )

    elements.append(Spacer(1, 25))

    # ------------------------------------------------
    # KPI Table
    # ------------------------------------------------

    elements.append(
        Paragraph(
            "Business KPI Summary",
            heading,
        )
    )

    elements.append(Spacer(1, 10))

    table_data = [
        ["Metric", "Value"],
        ["Total Sales", f"${kpis['sales']:,.2f}"],
        ["Total Profit", f"${kpis['profit']:,.2f}"],
        ["Total Orders", f"{kpis['orders']:,}"],
        ["Average Sales", f"${kpis['average_sales']:,.2f}"],
    ]

    table = Table(table_data, colWidths=[220, 180])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("BOTTOMPADDING", (0, 1), (-1, -1), 8),
        ])
    )

    elements.append(table)

    elements.append(Spacer(1, 25))

    # ------------------------------------------------
    # AI Summary
    # ------------------------------------------------

    elements.append(
        Paragraph(
            "AI Executive Summary",
            heading,
        )
    )

    elements.append(Spacer(1, 10))

    elements.append(
        Paragraph(
            ai_summary.replace("\n", "<br/>"),
            body,
        )
    )

    elements.append(Spacer(1, 30))

    # ------------------------------------------------
    # Footer
    # ------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Generated by InsightIQ</b>",
            styles["Heading3"],
        )
    )

    elements.append(
        Paragraph(
            "Confidential Business Report",
            styles["Italic"],
        )
    )

    doc.build(elements)